name: Raft

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cargo_flag: ["", "--release"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
      - name: install components
        run: rustup component add rustfmt clippy
      - name: check
        run: make check
        env:
          CARGO_FLAG: ${{ matrix.cargo_flag }}
      - name: test_2a
        run: LOG_LEVEL=raft=warn make test_2a
        env:
          CARGO_FLAG: ${{ matrix.cargo_flag }}
      - name: test_2b
        run: LOG_LEVEL=raft=warn make test_2b
        env:
          CARGO_FLAG: ${{ matrix.cargo_flag }}
      - name: test_2c
        run: LOG_LEVEL=raft=warn make test_2c
        env:
          CARGO_FLAG: ${{ matrix.cargo_flag }}
